version: '3.8'

services:
  app:
    build: .
    container_name: yii2_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: yii2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortlink_qr
    ports:
      - "3306:3306"